### ISSUE TITLE
Suggestions on value comparisons

### ISSUE THREAD

**Issue by TChatzigiannakis** [mjsabby/LLVMSharp#10]
Suggesting to introduce intuitive value comparisons for all LLVM types (structs and classes), reasoning: 

1. The C API structs' only job is to reference the internal data structures of LLVM. Thus, it makes sense that two struct instances that point to the same internal data structure of LLVM (same type, for example), should compare as equal.
2. The OOP API classes' only job is to wrap around the C API structs. Moreover, due to various implicit conversions we have introduced, class instances can trivially expose their struct instance and struct instances can trivially be wrapped as class instances. Thus, again, we can very easily end up with two separate instances of `Type` (for example) that, in fact, point to the same internal data structure of LLVM. Such instances should also compare equal, since they operate on the same data and any change to one will immediately be observable using the other.

**Comment by mjsabby** [comment]
Yes, I agree. Implementing IEquatable<T> is a fine next step.

Just to be clear, I still want to keep the struct-style API available for 2 reasons:

(1) Previous users of LLVMSharp

(2) Prior to the implicit conversions, we were not allocating managed objects, but now the implicit conversion cause boxing, which some people may not want, including my own internal use-case.

So if you're adding code around here, I ask you to design it in a way that I can still use the old API

**Comment by TChatzigiannakis** [comment]
I use the C API as well and I definitely don't want it to change in a breaking manner. I believe the above changes won't be breaking for the C API, since we will only be adding new members to the structs, enabling operations that right now are compile-time errors (for example, comparing two `LLVMValueRef` instance using `==` is an error in the last release). And if we are careful about which conversions are included in the release, the semantics of existing source files should remain the same.

About the boxing in the OOP API: it concerns me as well. Do you think it should be steered it towards something different? Maybe each type in the OOP API could keep track of the things it contains, and return those when asked (instead of querying the LLVM DLL and boxing the returned struct)? However, if we do this and then two different but "equal" instances from the OOP API (that point to the same LLVM data structure) start having out-of-sync information, bad things may happen.

**Comment by mjsabby** [comment]
Ok, good.

As you point out, if we go and build custom code inside our API then we risk being out of date (or worse even wrong) with LLVM's APIs. So I'm definitely not in favor of this, I've done it in a few places like Function and BasicBlock, which are admittedly not that great, but were needed.

I think the issue you have opened should track the IEquatable and Equals/GetHashCode/== operator we need to make for the managed and struct types.

The boxing issue ... well let's leave that discussion till when our API is complete and usable :)

**Comment by mjsabby** [comment]
I think we have a handle on this with the changes you made. Closing.
