### ISSUE TITLE
Suggestion to change implicit operator bool(LLVMValueRef) to explicit

### ISSUE THREAD

**Issue by TChatzigiannakis** [mjsabby/LLVMSharp#11]
There is an `implicit operator bool(LLVMValueRef)`. I suggest we make it explicit (and change its call spots to include a cast), for the following reasons:

1. Converting from a pointer to a boolean causes information loss (unlike our other implicit conversions, which happen between practically interchangeable data types, at no information loss). [According to MSDN][1], conversions that lose information should be explicit.
2. Right now any comparison of `LLVMValueRef` instances using `==` will go to `operator==(bool, bool)`. As far as I can tell from the code (I haven't tested it further), this will return `true` for any non-null-pointing instances, even if they point to completely different LLVM data structures. This serves us (for building the OOP API) but it's unintuitive to a user of the C API.

[1]:https://msdn.microsoft.com/en-us/library/xhbhezf4.aspx

**Comment by mjsabby** [comment]
I actually propose we remove it all together. I did it to get the automated code compile and run my small test app.

Removing it means we'll need to fix up the code, but that's what I was intending to do.

**Comment by mjsabby** [comment]
Closing this as you did this, Thanks!
