### ISSUE TITLE
Suggesting removal of implicit conversions between C and C++ API types

### ISSUE THREAD

**Issue by TChatzigiannakis** [mjsabby/LLVMSharp#20]
Even though there is no information loss between our boxed and unboxed types, I suggest we start gradually removing our implicit conversions.

* For trivial conversions (such as an `IRBuilder` to an `LLVMBuilderRef`), we could just have a class constructor and optionally, for the opposite case (`LLVMBuilderRef` to `IRBuilder`) expose the value as a `get`-only property (and it should be consistent for all our wrapper types).
* For non-trivial conversions (such as the `Value` hierarchy and `LLVMValueRef`), we could have a method that contains the logic we already have.

My reasoning is that (a) we avoid introducing unintended boxing, (b) we'll make it harder for client code to accidentally mix the two APIs, (c) we'll have a clearer view of what's currently missing from the C++ API, so that we can know what to add (d) it will make our code base cleaner.

If it sounds okay, I can make a PR that contains some of the changes.

**Comment by mjsabby** [comment]
It sounds okay.

**Comment by mjsabby** [comment]
Thanks!
