### ISSUE TITLE
LLVM.InitializeAll*() functions don't exist in the bundled libLLVM.dll (nuget)

### ISSUE THREAD

**Issue by TChatzigiannakis** [mjsabby/LLVMSharp#4]
I've found a list of functions that are declared in LLVMSharp 3.6.0 but they are not visible in the x86 or x64 version of the libLLVM.dll provided in the nuget package. Calling them throws a `System.EntryPointNotFoundException`. Their absence can also be verified using Dependency Walker.

The functions in question are:

- LLVM.InitializeAllTargets()
- LLVM.InitializeAllTargetInfos()
- LLVM.InitializeAllTargetMCs()
- LLVM.InitializeAllAsmPrinters()
- LLVM.InitializeAllAsmParsers()
- LLVM.InitializeAllDisassemblers()

The corresponding functions for individual targets are available, as expected.

**Comment by mjsabby** [comment]
Thanks for the bug report. You are right, the exports.def is not picking up these functions. I've not yet investigated why, but that is the reason why it's not in the dll.

You have two options:

(1) Hack the GenLLVMDLL.ps1 to stop on the exports.def generation, add these functions then call the linker
(2) Add it in your client code to just loop and call the target functions (I know, it sucks ..)

I'm going to take a look at this tomorrow to see what is going on in here.

**Comment by TChatzigiannakis** [comment]
It's not a problem to work around this from client code (especially using reflection, to automate the lookup and invocations).

I just found a few more:

- LLVM.InitializeNativeTarget()
- LLVM.InitializeNativeAsmPrinter()
- LLVM.InitializeNativeAsmParser()
- LLVM.InitializeNativeDisassembler()

The rest seem to be available, unless I've missed anything.

**Comment by mjsabby** [comment]
I looked at this, and it is because of the macro expansion happening the header files. The Windows build do not have these, so I think I'll need to put a hack in to suppress pushing these as an available API.

**Comment by mjsabby** [comment]
Alright, this has been fixed. https://www.nuget.org/packages/LLVMSharp/3.7.0-rc4-final

We can now change the LLVMSharp Intro example to:

            LLVM.InitializeNativeTarget();
            LLVM.InitializeNativeAsmParser();
            LLVM.InitializeNativeAsmPrinter();
            LLVM.InitializeNativeDisassembler();
            LLVM.LinkInGC();

**Comment by mjsabby** [comment]
Fixed with 3.7 release, available here: https://www.nuget.org/packages/LLVMSharp/3.7.0
