### ISSUE TITLE
Update bindings to LLVM 3.8

### ISSUE THREAD

**Issue by pragmascript** [mjsabby/LLVMSharp#48]
LLVM 3.8.0 was released and it would be nice if the bindings could be updated to the current version

**Comment by TChatzigiannakis** [comment]
Before that happens, I'd like to call attention to [this issue](https://github.com/mjsabby/LLVMSharp/issues/47) because fixing it is a _breaking change_ to the public API. If we decide to fix it, it might be best to do it now that a new version is coming.

**Comment by mjsabby** [comment]
Yes, that's a bummer. Ok, we'll plan to get this to 3.8 in the next few days.
