### ISSUE TITLE
Recursive struct type

### ISSUE THREAD

**Issue by Ryuuke** [mjsabby/LLVMSharp#51]
Hello Im wondering how we can handle recursive struct types, like this for exampe : 
`%player = type { %player, i32, etc... }`

**Comment by mjsabby** [comment]
LLVMSharp is currently closely mirroring the C API so some stuff is awkward C#, but we're working on improving that situation, while keeping the old APIs always available.

That said, here's a quick example:

```
var arr = new LLVMTypeRef[2];
var player = LLVM.StructType(arr, Packed: False);
arr[0] = player;
arr[1] = LLVM.Int32Type();
```

**Comment by Ryuuke** [comment]
Thanks :)
